site: blog.yorrick.dev
title: blog.yorrick.dev
greetings: Yorrick Bakker
description: >-
  I'm an IT consultant at Info Support in the Netherlands. I write about stuff that interests me here.
lang: en-US
timezone:  Europe/Amsterdam
data-theme: dark

author:
  name: Yorrick Bakker
  bio: I'm an IT consultant from the Netherlands
  github: ysbakker
  email: hi@yorrick.dev

# Font Settings
googlewebfonts: family=Montserrat:wght@400;700&family=Source+Code+Pro:ital,wght@0,200;0,300;0,400;0,600;0,700;0,900;1,300;1,400;1,500;1,600;1,700;1,900

# URL settings
url: "https://blog.yorrick.dev"
baseurl: ""
permalink: pretty

# local
# url: "http://localhost:4000"
# baseurl: ""

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false


