title: blog.yorrick.dev
email: hi@yorrick.dev
author: Yorrick Bakker
description: >-
  This is my tech blog. I sometimes write something here. Sometimes in Dutch, sometimes in English.
baseurl: ""
url: "https://blog.yorrick.dev"
show_excerpts: true

theme: texture

texture:
  title: Yorrick Bakker
  tagline: Software Engineering Student
  date_format: "%b %-d, %Y"
  style: "blue"
  showPicker: false
  showNav: true
  navigation:
    - title: Home
      url: "/"
    - title: About
      url: "/about"

  social_links:
    github: ysbakker
    linkedIn: in/yorrick-bakker-203938173/

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
